### ISSUE TITLE
URL Encoding of Slashes '/' - bug?

### ISSUE THREAD

**Issue by petermeissner** [Ironholds/urltools#16]
Hey, nice work ... 

In you example you use something like this:

```r
url_encode("https://de.wikipedia.org/wiki/Käse")
## [1] "https://de.wikipedia.org%2fwiki%2fK%e4se"
```
... which encodes the *Ä* but also the slashes making it basically a non-working URL. Is this known/wanted/cannot be prevented or did some bugs creep in? (without encoding the slashes, the URL work: http://de.wikipedia.org/wiki/K%e4se )

**Comment by Ironholds** [comment]
That's interesting! It looks like the first slash needs to be unencoded, which makes sense but raises interesting questions like "again, how is URLencode expected to be useful". I'll do some fiddling :)

**Comment by Ironholds** [comment]
@petermeissner see if the development version works for ya?

**Comment by petermeissner** [comment]
Many thanks. 

Interesting, I thought it would again not work because the last slash was encoded but it works for me.

```r 
browseURL( url_encode( "https://de.wikipedia.org/wiki/Käse" ) )
```

... Concerning the encoding / not encoding of slashes: I just had a glimpse on the RFC (https://tools.ietf.org/html/rfc3986#page-11) and I am not 100% sure but slashes (they are stated as reserved characters) and should always be used as separators in the *scheme-domain-port-path part* of the URL. Therefore, would it not be an idea to not encode slashes (and the other reserved characters) within those by default? It might be another story for the parameter values because here slashes and the other characters might serve as value and not as part of the scheme. Just some thoughts.

**Comment by Ironholds** [comment]
IOW, only encode within parameter and query fragments? Makes total sense; I'll patch now.

**Comment by Ironholds** [comment]
Okay, looking at this further; variable charsets are a PITA to build and it doesn't actually seem to be breaking things. Nor should it be breaking things; that's a fairly common convention even if it isn't in the RfC. So I'm going to mark it "resolved" for now, and if people can point to things other than poorly-configured Apache servers that it breaks, I'll reopen.
