### ISSUE TITLE
[FR] url_compose()

### ISSUE THREAD

**Issue by npjc** [Ironholds/urltools#18]
Apologies if there's already an awesome way to do this.

Compose a url from it's parsed data.frame

#### round-trip !
```r
"https://en.wikipedia.org/wiki/Article" %>%
    url_parse() %>%
    url_compose()
#> [1] "https://en.wikipedia.org/wiki/Article"
```

**Comment by Ironholds** [comment]
There isn't! What's the use case?

**Comment by nicolasCoutin** [comment]
Some thoughts: (but perhaps i just quite like the symmetry of it.)
- parse urls (API requests, FTP urls) then use joins (dplyr) for filtering / expansion... then recompose
- pass a data.frame around building/modifying urls then compose.

**Comment by Ironholds** [comment]
That makes sense. Could you give some examples so I know what sort of feature set you're looking for? On the modification of URLs, we have the accessors (port(url) and such)

**Comment by nicolasCoutin** [comment]
(disclaimer: this feature is really just a nicety as this can all be done other ways but I quite like data.frames...)

##### 1. parse_urls and expand upon combinations of their parts then recompose.

```r
urls <- c('http://www.yeastgenome.org/locus/S000005366/overview#protein',
          'http://www.yeastgenome.org/locus/S000005356/overview#interaction',
          'http://www.yeastgenome.org/locus/S000005226/overview#overview')

url_parse(urls) %>% 
  tidyr::expand_(names(.)) %>% 
  url_compose()

#> [1] "http://www.yeastgenome.org/locus/s000005226/overview#interaction"
#> [2] "http://www.yeastgenome.org/locus/s000005226/overview#overview"   
#> [3] "http://www.yeastgenome.org/locus/s000005226/overview#protein"    
#> [4] "http://www.yeastgenome.org/locus/s000005356/overview#interaction"
#> [5] "http://www.yeastgenome.org/locus/s000005356/overview#overview"   
#> [6] "http://www.yeastgenome.org/locus/s000005356/overview#protein"    
#> [7] "http://www.yeastgenome.org/locus/s000005366/overview#interaction"
#> [8] "http://www.yeastgenome.org/locus/s000005366/overview#overview"   
#> [9] "http://www.yeastgenome.org/locus/s000005366/overview#protein"   
```

(N.B. with the above examples 'interaction', 'overview', and 'protein' end up in the `parameter` ... should this not be in `fragment`? I'm probably just confused...moving on)

##### 2. Composing _de-novo_ if you will...

Here I query an API for all the datasets satisfying a certain condition (receiving a data.frame of the results). To actually get the files from their FTP site I need to build these details with their specified formatting (where only _some_ of the special symbols are url-encoded while others are not) and then use it as the `path` argument in a url. __Here it would be useful to allow for only partial specification:__ where if you don't provide the bits you don't need (if no `port`, etc... is provided it still works).

```r
df <- dplyr::data_frame(...)
ftp_file_urls <- url_compose(df)
```

**Comment by Ironholds** [comment]
Huh, they do! A fun bug; I'll dig into it :)

**Comment by Ironholds** [comment]
@npjc so I actually have all of them in the path except protein, which is in parameter (and should be in fragment). Will work on a bugfix now :)

**Comment by Ironholds** [comment]
The fragment issue should be resolved with the latest version :). I'll split out the recompose feature into a new issue.

**Comment by Ironholds** [comment]
And we should now have URL composition! Please do test it out and let me know if it breaks anywhere :)

**Comment by npjc** [comment]
@Ironholds awesome! Will do.
