### ISSUE TITLE
punycode handling

### ISSUE THREAD

**Issue by hrbrmstr** [Ironholds/urltools#19]
For:

`urltools::suffix_extract("xn--80aagrchk9a2a2a.xn--p1ai")`

this:

                              host subdomain domain  tld
    1 xn--80aagrchk9a2a2a.xn--p1ai      <NA>   <NA> <NA>

should not be the outcome.

might want to handle punycode encoding & decoding at the same time (perhaps [via](https://github.com/bnoordhuis/punycode/blob/master/punycode.c))

**Comment by Ironholds** [comment]
What the heck is punycode? 

*reads*

Okay, that's weird as heck. Embedding a punycode solver makes sense but I should do some tests to see what including it by _default_ does to the speed.

**Comment by Ironholds** [comment]
Just a note that having reviewed the available punycode solvers and how unicode works that low down the PL food chain, I'm not planning on actively working on this; frankly, it's a bit beyond me :(. If someone more C-literate wants to PR it I'm happy to include and add as an author.

**Comment by alexcpsec** [comment]
This is done, right? We handled it on the `punycode` package

**Comment by Ironholds** [comment]
Yep! We should recommend punycode, though.

**Comment by alexcpsec** [comment]
Can you do the "recommending"? I have no idea how these fancy R Package things work.

**Comment by Ironholds** [comment]
Looks like "no, punycode isn't on CRAN". Otherwise I'd stick it in "suggests". Womp womp :(

**Comment by hrbrmstr** [comment]
It's gonna be a bit before punycode gets on CRAN. I've got a Windows pkg
ref I can use now but it's a lower priority item.

**Comment by alexcpsec** [comment]
No worries on that, Perhaps we should just add a warning / suggestion to get it from GitHub on the readme and call it a day?
