### ISSUE TITLE
url_encode only certain characters.

### ISSUE THREAD

**Issue by npjc** [Ironholds/urltools#21]
### Synopsis

I want to be able to efficiently encode a specified set of characters:

 - eg. only encode `#` and `:`

```r
uniform_name <- 'example=idenfitier#with:odd_format.gff3,gz'

urltools::url_encode(uniform_name, only = c(':', '#'))
#> [1] "example=idenfitier%23with%3Aodd_format.gff3,gz"


# OR equivalently...
urltools::url_encode_chars(uniform_name, c(':', '#'))
```

### Current Use Case

Consider the following unique identifier for a file:

```r
uniform_name <- "H1:Cell-Line=S2-DRSC#Developmental-Stage=Late-Embryonic-stage#Tissue=Embryo-derived-cell-line:ChIP-chip:Rep-1:input:Dmel_r5.32:modENCODE_3300:12_A8_Input.62.CEL.gz"
```

`uniform_name` is the name of a file at:
```r
ftp_dir <- "ftp://data.modencode.org/D.melanogaster/Histone-Modification/ChIP-chip/raw-arrayfile_CEL/"
```

With the data above I should be able to download the file with `curl::curl_download()` or equiv. BUT, I can't b/c the metadata I have access to (`uniform_name`,...) actually represents a user-facing link. To actually download the file I need to transform `uniform_name` to:

```r
transformed_uniform_name <- "H1%3ACell-Line=S2-DRSC%23Developmental-Stage=Late-Embryonic-stage%23Tissue=Embryo-derived-cell-line%3AChIP-chip%3ARep-1%3Ainput%3ADmel_r5.32%3AmodENCODE_3300%3A12_A8_Input.62.CEL.gz"
```

Yupp, the download url is only "partially encoded" (only `:` and `#` are encoded). So do make `transformed_uniform_name` I currently do something like)

```r
stringi::stri_replace_all_fixed(uniform_name, ':', urltools::url_encode(':'))
# and again with '#' ...
```

This is unsatisfying to say the least. It would be great if I could do something like:

```
urltools::url_encode(uniform_name, only = c(':', '#'))
# OR...
urltools::url_encode_chars(uniform_name, c(':', '#'))
```

This way collaborators and future me don't have to spend time figuring out why I wasn't just encoding the url properly.

**Comment by Ironholds** [comment]
Huh. So, the thing doesn't work if you fully encode? :/ What system is this and why doesn't it recognise encoding?

**Comment by npjc** [comment]
Modencode. 100s of millions. Science for the win.  But it's true. Unfortunately.

**Comment by Ironholds** [comment]
I mean, I can happily provide you with a little piece of C++ that'll handle your specific task - but I'm not seeing a wide use case for modifiable encodings. People _should_ be using standardised encoding. Like I said, though, happy to put together a mod_encode() and mod_decode() function pair for ya :)
