### ISSUE TITLE
url_parse fails to separate port without trailing slash

### ISSUE THREAD

**Issue by richfitz** [Ironholds/urltools#31]
```
> url_parse("http://localhost:8000")
  scheme         domain port path parameter fragment
1   http localhost:8000                             
> url_parse("http://localhost:8000/")
  scheme    domain port path parameter fragment
1   http localhost 8000                        
```

I'm in no way a URL nerd, but this looks in violation of [the rfc](http://www.ietf.org/rfc/rfc3986.txt)

>      authority   = [ userinfo "@" ] host [ ":" port ]

>    URI producers and normalizers should omit the ":" delimiter that
>    separates host from port if the port component is empty.  Some
>    schemes do not allow the userinfo and/or port subcomponents.

>    If a URI contains an authority component, then the path component
>    must either be empty or begin with a slash ("/") character.  Non-
>    validating parsers (those that merely separate a URI reference into
>    its major components) will often ignore the subcomponent structure of
>    authority, treating it as an opaque string from the double-slash to
>    the first terminating delimiter, until such time as the URI is
>    dereferenced.

(also why are they requests for *comments* if they're meant to be authoritative I don't understand).

**Comment by Ironholds** [comment]
Ooh, interesting! Great catch! Patching now (and adding unit tests for regression)
