### ISSUE TITLE
Case sensitivity in paths/routes not honoured by url_compose

### ISSUE THREAD

**Issue by 17843** [Ironholds/urltools#32]
Hi, great package, thank you!

There's an issue though where 

    url_compose(
      url_parse("http://www.example.com/Route")
    )

produces `[1] "http://www.example.com/route` 

Many paths and queries are indeed case sensitive, see http://tools.ietf.org/html/rfc3986#section-6.2.2.1 for reference.

**Comment by Ironholds** [comment]
Good catch! I'll work on it :)
