### ISSUE TITLE
Reinstate `suffix_refresh()` returning an object with the updated suffix list

### ISSUE THREAD

**Issue by alexcpsec** [Ironholds/urltools#33]
Here is the idea we discussed about updating the suffix list:

1) Have `suffix_refresh()` back returning a data[frame/table] object on the same format as the internal object format used by `suffix_extract()`.
2) Make `suffix_extract()` have an optional argument `suffix_list` that defaults to the internal object

No need to update the internal object and someone that needs up-to-date info can use it without worry.

**Comment by Ironholds** [comment]
You owe me a drink :P

**Comment by alexcpsec** [comment]
All the drinks. :)
