### ISSUE TITLE
Handling of NAs by url_parse and url_compose

### ISSUE THREAD

**Issue by asieira** [Ironholds/urltools#38]
I ran into this behavior today that I thought could be improved:
```
> str(url_parse(c("http://www.google.com", NA_character_, "")))
'data.frame':	3 obs. of  6 variables:
 $ scheme   : chr  "http" "" ""
 $ domain   : chr  "www.google.com" "na" ""
 $ port     : chr  "" "" ""
 $ path     : chr  "" "" ""
 $ parameter: chr  "" "" ""
 $ fragment : chr  "" "" ""
> url_compose(url_parse(c("http://www.google.com", NA_character_, "")))
[1] "http://www.google.com/" "na/"                    ""     
```

I would like to suggest that `url_compose(url_parse(NA_character_))` be made to return `NA_character_` for consistency. 

Maybe this could be done by having `url_parse` return a row with all NAs, which `url_compose` then checks for.

**Comment by Ironholds** [comment]
Good news: I am fixing this! url_decode and url_encode handle NAs nicely now.

Bad news: it is a pain ;p. I'll let you know when I've worked out the solution.

**Comment by asieira** [comment]
:+1: :heart:
