### ISSUE TITLE
custom URL protocol handlers support

### ISSUE THREAD

**Issue by hute37** [Ironholds/urltools#39]
It would interesting if could be some support of coston protocol handles

A function repository of custom connection management

```R
    URLS(proto='custom', handler = function(url) ... return(con)
```

```R
    con <- URL("custom://...").open()
```

I've post a question on StackOverflow:

http://stackoverflow.com/questions/34903379/r-custom-url-protocol-handlers

**Comment by hrbrmstr** [comment]
What would be the use-case? i.e. when would you need to parse those URLs? (I'm not suggesting this shouldn't be done but am trying to think of a practical use-case).

**Comment by hrbrmstr** [comment]
oh, now i see :-)

**Comment by Ironholds** [comment]
I sort of see the use case but I really can't think of a good way of elegantly defining those, nor a wide enough use of the use case. I'm pretty sure there's already a package designed for filepath manipulation, for example.

**Comment by hute37** [comment]
Well, I think the point in not to provide URL handlers. This is too hard to generalize.
IMHO, a nice addition would be the introduction of a *common*  way to "register" a custom handler with a "well-defined" *interface*.

For some protocols, the specs are rather clear. The **data://** input protocol is specified here:

* https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Data-in-packages

Another example could be something like

 * **cran://package/path**
 * **help://package/man/entry?accept=application/pdf**

All with an *implied* **GET** method for read.

A well defined *interface* may help standard implementations for well defined contexts:

```R
df <- lapply(c( 'data://pkg1/ds1','http://host/ds2.txt','sftp://host2/ds3.txt','fifo:///tmp/zzz'), function(url) read.table(URL(url))
```

**Comment by Ironholds** [comment]
Sure; these definitely seem useful in certain contexts, I'm just saying that they don't, to me, fit within the scope of this package. This doesn't mean another dedicated package might not be really cool.

**Comment by hute37** [comment]
I agree that a dedicated package would be better
This package should have only urltools as dependency and just provide only some base implementation of URL handlers 

Additional packages can include additional dependecies as needed:

 * **sftp://** based on *RCurl* or *ssh.util*
 * **ssh://** based on *ssh.util* run.remote

I'll comment on original thread:

http://stackoverflow.com/questions/34903379/r-custom-url-protocol-handlers

**Comment by Ironholds** [comment]
Yeah, a sort of universal work-out-what-kind-of-con()-to-use-with-this-handler would be super cool!
