### ISSUE TITLE
build tld_extract to go along with suffix_extract

### ISSUE THREAD

**Issue by soodoku** [Ironholds/urltools#41]
Dear Oliver,

It would also be nice to support TLD parsing. 

I agree that is a bit of a crapshoot, but I think it would be nice to have some support for it. 

Warmly

**Comment by Ironholds** [comment]
Define parsing in this context?

**Comment by soodoku** [comment]
Inapt use of the word. I meant really, it would be cool to have a function that tries to get the user the tld.  Modeled a bit like suffix_extract but limited to best guess tld.

**Comment by Ironholds** [comment]
Ahh, gotcha. Could be fun! I'll see what I can do.

**Comment by Ironholds** [comment]
Update: actively working on this indirectly! Basically I'm building a trie implementation, at https://github.com/Ironholds/triebeard , which should make C++-side partial-matching trivial.

**Comment by Ironholds** [comment]
@soodoku okay, prototyped the approach by making improvements to suffix_extract (quite successfully!)

Do you want *literally* the top level domains? IOW, "foo.co.uk" would come out as "uk", not "co.uk", because .co is a SLD.

**Comment by soodoku** [comment]
nice, @Ironholds! 

Great point. It may be nice to provide both sld and tld.

Thank you for working on this.

**Comment by Ironholds** [comment]
Well, that's covered by the public suffix list, really.

**Comment by soodoku** [comment]
I meant having the two in separate columns. 

When I go here for instance: https://publicsuffix.org/list/public_suffix_list.dat

I don't see an easy to pry the two apart.

But tld would be useful in itself.

To give you a better sense of one of the use cases, I am building a domain classifier using just features of the domain name. See for instance,

https://github.com/soodoku/domain_classifier/tree/master/name_and_content

And I believe having a more granular way to break up the domain name would be useful.

**Comment by Ironholds** [comment]
Hrn; that's likely to be a pain. TLDs is easy; TLD and secondary is likely to be duplicative, slow down suffix extraction, or both.

**Comment by soodoku** [comment]
Got it. Thanks. Let us go with TLD then, for now. And it makes complete sense to impute SLD from data we already get from suffix_extract + TLD. 

And very happy to defer to your judgment.

**Comment by hrbrmstr** [comment]
while this is back in dev-mode, it'd be handy to return the host (first
chars up up to first `.`) as well. i was gonna add that in a week or so
(lots of meetings this week)

**Comment by Ironholds** [comment]
So, host-within-domain?

**Comment by Ironholds** [comment]
Surely that'd just be lapply(strsplit(domain(urls_go_here), "."), function(x){return(x[length(x)]))?

I mean, we can optimise it but it seems like a very easy-peasy thing for users to do themselves.

**Comment by hrbrmstr** [comment]
it'd be super-handy to have it as part of the returned data frame.

**Comment by soodoku** [comment]
Thanks, O!
