### ISSUE TITLE
internationalized domain name support

### ISSUE THREAD

**Issue by soodoku** [Ironholds/urltools#42]
Dear Oliver,

I don't think this is as much of a priority but it may be a useful feature as use of idns catches on. More here: 
https://en.wikipedia.org/wiki/Internationalized_domain_name
and here: https://www.icann.org/resources/pages/idn-2012-02-25-en

Warmly

**Comment by Ironholds** [comment]
Aye, punycode integration is something we want but need to scream frustratedly at :D

**Comment by soodoku** [comment]
:-)

Haven't looked at this closely but one solution may be to rely on this C lib: 
http://www.gnu.org/software/libidn/doxygen/punycode_8c_source.html

But I take yr. point

**Comment by Ironholds** [comment]
Which is GNU-licensed; I've looked into it. There's an MIT-licensed library I've been investigating but haven't worked out how to have play nice yet.

**Comment by hrbrmstr** [comment]
aye. Jeroen's enabled Win lib support of the GNU one I put into
https://github.com/hrbrmstr/punycode but C++ + Unicode + R is ugh in
general even without the lib support.

**Comment by Ironholds** [comment]
What's the specific ugh here?

**Comment by hrbrmstr** [comment]
Getting unicode into and out of C to R well and fast.

**Comment by okeyes-r7** [comment]
Argh or not, is it CRAN levels of portable now?

**Comment by Ironholds** [comment]
I wonder if porting https://github.com/bestiejs/punycode.js/blob/master/punycode.js would be least-sucky

**Comment by Ironholds** [comment]
https://dxr.mozilla.org/mozilla-central/source/netwerk/dns/punycode.c appears to be openly licensed too. hmn.

**Comment by Ironholds** [comment]
This is now added thanks to Drew; I need to do some cleanup around error-versus-warning elegance and documentation, I think, but otherwise is good to go!
