### ISSUE TITLE
Not passing all of the public suffix list tests

### ISSUE THREAD

**Issue by jayjacobs** [Ironholds/urltools#45]
Did an informal run against the tests at https://gist.github.com/jayjacobs/ca53a484d1b8d7217ef8b4a3ecc5c00b

37 of the 85 tests failed. 
The cobbled together code I wrote will grab the tests and run them through suffix_extract.

**Comment by Ironholds** [comment]
So we can fix a couple of the bugbears with two tweaks:

1. Lowercasing the domains before scanning them (this is probably good practice generally);
2. Setting suffix to NA when the suffix match's size is the entire string.

Together these get it down from 37 to 21 failures.

The remainder are fixable! But only by introducing special cases that dramatically increase the complexity of the codebase and require a load of additional operations for each query. And most of them are actually not domains - they're "someone provided *only* the suffix as a domain, it should object to that". I don't expect people to see that much in "production".

**Comment by alexcpsec** [comment]
I'll give you a report on that (prod sightings) if you don't mind. I am running urltools-like code on my stuff for millions of customer visited domains per day.

**Comment by Ironholds** [comment]
Sounds good!
