### ISSUE TITLE
set new component does not work on NA component

### ISSUE THREAD

**Issue by cderv** [Ironholds/urltools#46]
Hi, 

I tried to construct a url by its components using set functionnality but it does not work if I have empty part in the URL. See example

``` r
library(urltools)
example_url <- "http://cran.r-project.org:80"
path(example_url)
#> [1] NA
path(example_url) <- "bin/windows/"
path(example_url)
#> [1] NA
example_url
#> [1] "http://cran.r-project.org:80"
```
I believe it should have work. What do you think?

**Comment by Ironholds** [comment]
This is a Hard Problem (tm) at least as I recall the code, but I'll take a
look at it when I'm back at a computer this coming weekend.
