### ISSUE TITLE
lower case in url_encode

### ISSUE THREAD

**Issue by kislenok-roman** [Ironholds/urltools#47]
Got a problem when using url_encode after url_decode. 
`urltools::url_encode(urltools::url_decode("%2B")) == "%2B" # FALSE`

Really we should have some parameter to control the case of the result, something like:
`urltools::url_encode(urltools::url_decode("%2B"), upper = TRUE) == "%2B" # TRUE`

With default value equal to `FALSE` to support current version

**Comment by Ironholds** [comment]
Could you provide the actual values involved as well as that it does not
match?

**Comment by kislenok-roman** [comment]
We identify users by strings like "7cf805c4bnz8vGbdj%2FMu2oZW%2BEvNQ0af" in Access Logs, but in other systems we store decoded values for identification ("7cf805c4bnz8vGbdj/Mu2oZW+EvNQ0af" for this example).

So if I need to find a user from logs in other tables I do:
`url_decode(USER_ID)` 
This'll give you "7cf805c4bnz8vGbdj/Mu2oZW+EvNQ0af".

But if some user of interest came from some of other tables with id in decoded form there are no way to find this user in Access Logs:
`url_encode("7cf805c4bnz8vGbdj/Mu2oZW+EvNQ0af")`
will give "7cf805c4bnz8vGbdj%2fMu2oZW%2bEvNQ0af" where "%2f" and "%2b" are in different case from "%2F" and "%2B" in original strings (and in logs).

**Comment by Ironholds** [comment]
I'll look into it when I get back from Texas. In this specific case why
don't you just compare both decoded values?

**Comment by Ironholds** [comment]
Alright, have looked into!

So, if this is fixable - theoretically everything is fixable but it looks like a ton of work - it's going to cause a lot of slowness for function users. Moreover, it's not actually necessary; the RFC on URL percent-encoding explicitly says the result should not be case-sensitive.

My suggestion would be to either _decode_ both and compare or, if you really need to be comparing the encoded versions, decode, then encode, then compare (which sounds like a pain but I don't know the constraints your work is under).
