### ISSUE TITLE
suffix_extract extracts the domain wrong

### ISSUE THREAD

**Issue by mkhezr** [Ironholds/urltools#48]
tried:  suffix_extract("http://www.converse.com") 
result : 
                     host  subdomain domain suffix
1 http://www.converse.com http://www  conve se.com

**Comment by Ironholds** [comment]
That shouldn't happen if you pass in a domain as the docs suggest, rather
than a URL. If it does, lemme know! I may have forgotten to implement the
point-matching feature. Oops >.>

**Comment by mkhezr** [comment]
It happens even when the result of domain is passed as opposed to a url:

suffix_extract(domain("http://www.converse.com"))
              host subdomain domain suffix
1 www.converse.com       www  conve se.com

**Comment by Ironholds** [comment]
Then yep, I messed up the period insertion to the trie! Thanks for finding
- I will tinker :)

**Comment by mkhezr** [comment]
Another example for your tests:

suffix_extract(domain("http://ca.shop.ecco.com"))
              host subdomain domain suffix
1 ca.shop.ecco.com   ca.shop      e co.com

**Comment by Ironholds** [comment]
Bah, yep, I see the problem -
https://github.com/Ironholds/urltools/blob/master/R/zzz.R#L7 should replace
it with a period.

I won't be able to fix this for at least a week
(login/auth/switching-laptops-and-travelling) buuut if you were to submit a
patch and jump up and down on the patched version to make sure it works, I
should be able to merge it!

On Fri, Aug 19, 2016 at 6:22 PM, Maryam Khezrzadeh <notifications@github.com

**Comment by alexcpsec** [comment]
Just FYI, I just hit the same issue. Please let me know if you are able to have a look at this anytime soon.

**Comment by Ironholds** [comment]
It'll be tomorrow or the next day, yup (it's a very simple patch, just not
one I can currently make with my hardware).

**Comment by alexcpsec** [comment]
Thanks, @Ironholds . Good news is that so far this was the only issue I found in testing the new code at scale. Processing time is looking great compared to my old code!

```
> length(dd)
[1] 85341
> system.time(resp1 <- dns.extractDomain(dd, type = "suffix", size=c(1)), gcFirst = TRUE)
   user  system elapsed 
 65.381  10.221  25.057 
> system.time(resp2 <- dns.extractDomain(dd, type = "urltools_suffix", size=c(1)), gcFirst = TRUE)
   user  system elapsed 
  0.881   0.072   1.756 
```

**Comment by mkhezr** [comment]
I have made a pull request.

**Comment by Ironholds** [comment]
This should now be fixed! Many thanks to both @alexcpsec and @mkhezr - your commentary and patches were invaluable, and both of you will be credited as package contributors in the next release version (which I'm sending out this evening!)
