### ISSUE TITLE
Should parameters not present in the URL be passed back as NA?

### ISSUE THREAD

**Issue by JoshIzzard** [Ironholds/urltools#49]
It seems that both parameters not in the URL, and parameters set equal to nothing will both be passed back as `""`: 

```{r}
myurl = "http://fios.verizon.com/hop.html?CMP=111&s_ace=&gclid=111"
out = param_get(myurl, c('s_ace', 's_stlnk'))
t(out)
# >         1 
# > s_stlnk ""
# > s_ace   ""
```

This is troubling for my use case, but more broadly I think it makes sense to have a query for a url parameter that is not there to return differently than one that is there, but is set to empty.

**Comment by JoshIzzard** [comment]
I am currently doing something like this to make it work for me - given a vector of urls `myurls` and a data frame `myparams = param_get(urls = myurls, parameter_names = c('s_ace', 's_stlnk')`
```{r}
existsthere = lapply(names(myparams), function(x) grepl(x, myurls, fixed = T)) %>% setNames(names(myparams))

for (nm in names(myparams)) {
  myparams[[nm]][ !existsthere[[nm]] ] = NA
}
```

**Comment by Ironholds** [comment]
Ahh, looks like a part of the NA rewrite I missed. Thanks for reporting
this; I'll try to get to it early next week when I have a laptop again.

**Comment by JoshIzzard** [comment]
No problem, thanks Oliver!

**Comment by Ironholds** [comment]
And appropriately I got to it early next week:

```
> myurl = "http://fios.verizon.com/hop.html?CMP=111&s_ace=&gclid=111"
> out = param_get(myurl, c('s_ace', 's_stlnk'))
> out
  s_ace s_stlnk
1          <NA>
```

Just promise me you'll stop using `=` ;)

**Comment by JoshIzzard** [comment]
I'll make it a New Year's Resolution for 2017 :)
