### ISSUE TITLE
tld_refresh is ignoring punycode TLDs

### ISSUE THREAD

**Issue by alexcpsec** [Ironholds/urltools#51]
There is a side effect from this line here https://github.com/Ironholds/urltools/blob/7b2c6c263e74b9eb501ace1935ee55f4612b7dfa/R/suffix.R#L195

It is removing not only lines with `#`, but also ones with `--`, including the `XN--*` lines that represent the punycode entries.

```
> ss
[1] "xn--80aa8argd0e.xn--80aswg"      "xn--80aadccbto5aw2bf4m.xn--p1ai" "xn--80aatgnxx.xn--80asehdb"     
> tld_extract(ss)
                           domain  tld
1      xn--80aa8argd0e.xn--80aswg <NA>
2 xn--80aadccbto5aw2bf4m.xn--p1ai <NA>
3      xn--80aatgnxx.xn--80asehdb <NA>
```

**Comment by Ironholds** [comment]
Ooh, fun! Will fix for the next release (probably tonight)

**Comment by Ironholds** [comment]
I don't get it. You mean that, as well as comments, it's excluding the punycode entries? That's because they're, well, stored as comments. What format should they be taking? I'm happy to include the xn-- entries (they look fairly standardised) if I know which _bit_ I should be including - punycode isn't something I encounter much of the time.

**Comment by alexcpsec** [comment]
Keep the “XN—*” entries. That is all there is to it.

On August 30, 2016 at 3:25:52 PM, Oliver Keyes (notifications@github.com)
wrote:

I don't get it. You mean that, as well as comments, it's excluding the
punycode entries? That's because they're, well, stored as comments. What
format should they be taking? I'm happy to include the xn-- entries (they
look fairly standardised) if I know which *bit* I should be including -
punycode isn't something I encounter much of the time.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Ironholds/urltools/issues/51#issuecomment-243601245>,
or mute the thread

**Comment by alexcpsec** [comment]
Maybe `pattern = "^(#|--)")` does the trick?

**Comment by Ironholds** [comment]
Ohhh I'm a total dolt. I've been looking at entirely the wrong dataset!
