### ISSUE TITLE
Harmless compiler warning on Windows

### ISSUE THREAD

**Issue by wrathematics** [Ironholds/urltools#59]
This is totally harmless, and isn't generating any R CMD check NOTEs or WARNINGs. That said, CRAN is **REALLY** tightening the screws on compiled code warnings, and I honestly wouldn't be surprised if at some point in the near future they start treating all warnings as WARNINGS (and may god help us all on that day).

I can't just c/p because it only shows up on windows. But the warning is in compose.cpp:58:29, "comparison between signed and unsigned integer expressions" at the <.  So `schemes.size()` is signed?  Dunno.

Personally I probably wouldn't do anything, so feel free to close the issue.  But if CRAN activates that warning/WARNING killswitch, you'll need to know about this.

**Comment by Ironholds** [comment]
Yeah, this I need to get on just so it ceases yelling - basically it's not that schemes.size() is signed, it's that it's an int, and different platforms have different standards for whether they default an int to signed or unsigned *eyeroll*. I can solve for this by just explicitly assigning to an unsigned - which, tbh, I should be doing anyway.

**Comment by wrathematics** [comment]
`int` should always be signed. It might not always be 32 bits, but it's definitely signed.
