### ISSUE TITLE
Document punycode functions (and improve error handling around them)

### ISSUE THREAD

**Issue by Ironholds** [Ironholds/urltools#61]

**Comment by Ironholds** [comment]
@wrathematics what (if any) is the C/++ equivalent of mkCharLen, do you know? Just looping through the char and appending until you hit a terminator or BUFFLEN?

**Comment by wrathematics** [comment]
I don't really understand the question. `mkChar` functions convert (with varying assumptions) `char*` data into `CHARSXP`. `mkChar` assumes a string, `mkCharLen` takes a buff and a length (does not check for nul). The CE variant sets character encoding. There's no direct equivalent because R uses that dumb string pool.

If you're trying to rewrite the wrapper in C++ (why though?), using Rcpp Attributes you would presumably just return the string. But you'll have to be careful about how the encoding is set.

**Comment by Ironholds** [comment]
That answered it; thankya! :)

The method to my madness - for proper IDN encoding/decoding we want to do a looot more than just punyencode the entire string - we want to be able to do things like split out non-host parts and then tokenise them and go through a whole set of nested possible manipulations to the resulting output string, which is kind of a pain in C (not impossible, obviously, but - string manipulation and C++ are easier friends).

**Comment by wrathematics** [comment]
Ahh, I see.

Might make more sense then to convert the C functions into `void`, rather than `SEXP` and just have them operate on the buffer data. Or would they still need to be directly user-callable? If so, a little wrapper shim could live on top for that purpose.

**Comment by Ironholds** [comment]
Yeah, that makes sense. What I've gone for so far, at least for experimental purposes, is just integrating the C functions logic into the middle of wider C++ that [operates on strings rather than chars, does all of that goodness, then a c_str() call and boom)

**Comment by wrathematics** [comment]
Well, sounds like you've got it under control. If I can help with anything else, let me know.

**Comment by Ironholds** [comment]
Shall do! It looks like it's working.

No way I can ship a load of whisky to TN? You've done a ton of work here.

**Comment by wrathematics** [comment]
That would be a strange journey for the whiskey, considering all the best stuff is made here ;)

Nah, I'm good. Happy to help!

**Comment by Ironholds** [comment]
A gift card? Something?! Bah :D

**Comment by wrathematics** [comment]
Nah, no worries. I had fun!
