### ISSUE TITLE
url_parse doesn't handle URLs with user:pwd in them

### ISSUE THREAD

**Issue by sckott** [Ironholds/urltools#64]
e.g., 

```r
urltools::url_parse("http://foo:bar@97.77.104.22:3128")
#>   scheme domain                  port path parameter fragment
#> 1   http    foo bar@97.77.104.22:3128 <NA>      <NA>     <NA>
```

maybe you don't plan to handle this?

**Comment by hrbrmstr** [comment]
Hrm. While I don't want to encourage the use of this, I can see useful cyber context for handling it.

I think we shld support this but perhaps also have a  `strip_uri_credentials()` filter function.

**Comment by sckott** [comment]
Sure, but i guess we can't prevent people from using that structure

**Comment by hrbrmstr** [comment]
Aye. We see it quite a bit in our honeypot logs and it'd be useful to both be able to strip these things but also analyze them.

**Comment by Ironholds** [comment]
I mean. That's a URI, but not a URL :P.

Direct support for this would involve...well, amongst other things massive changes to the code and alterations to the output format that are unlikely to be useful for the vast majority of cases. I can see parse_authority and parse_userinfo as new functions, maybe?

**Comment by hrbrmstr** [comment]
that's one reason I initially was going to suggest just a "strip/remove" function. I've got a regex for this, tho, so at least extracting them won't be at all "work".

**Comment by hrbrmstr** [comment]
I shld pt out that I _did_ note it'd be `strip_uri_credentials()` above ;-p

**Comment by sckott** [comment]
at the very least stripping the credentials before parsing would be good so the output from 
`url_parse` is correct

**Comment by Ironholds** [comment]
This is fair!

**Comment by Ironholds** [comment]
Okay, so looking at it I'm thinking of implementing:

1. A minor change to the parser that would just totally discount credential information;
2. A strip_credentials function if the user reaaally wants to be sure they're gone;
2. A get_credentials function that retrieves 'username' and 'password' as a df

Thoughts?

**Comment by hrbrmstr** [comment]
If you have the cycles to do that, it'd be ++gd IMO. If I weren't teaching
I'd actually offer to jump in on one of them but I've lost the concept of
"free time" at this point ;-)

**Comment by sckott** [comment]
sounds bueno.
