### ISSUE TITLE
Extract domain properly when domain is an IPv6 address

### ISSUE THREAD

**Issue by alexcpsec** [Ironholds/urltools#65]
Sorry I keep breaking your stuff, @Ironholds 

```
Browse[1]> urltools::url_parse("tcp://24.188.179.19:8333")
  scheme        domain port path parameter fragment
1    tcp 24.188.179.19 8333 <NA>      <NA>     <NA>
Browse[1]> urltools::url_parse("tcp://[2607:5300:61:44f::]:8333")
  scheme domain                port path parameter fragment
1    tcp  [2607 5300:61:44f::]:8333 <NA>      <NA>     <NA>
```

**Comment by Ironholds** [comment]
Wh. Whaaaa...

I'll see if I can think of an unambiguous way to parse this.

**Comment by hrbrmstr** [comment]
This is actually what it has to handle:

    host = IP-literal / IPv4address / reg-name

    IP-literal = "[" ( IPv6address / IPvFuture  ) "]"

    IPvFuture  = "v" 1*HEXDIG "." 1*( unreserved / sub-delims / ":" )

    IPv6address =                              6( h16 ":" ) ls32
                  /                       "::" 5( h16 ":" ) ls32
                  / [               h16 ] "::" 4( h16 ":" ) ls32
                  / [ *1( h16 ":" ) h16 ] "::" 3( h16 ":" ) ls32
                  / [ *2( h16 ":" ) h16 ] "::" 2( h16 ":" ) ls32
                  / [ *3( h16 ":" ) h16 ] "::"    h16 ":"   ls32
                  / [ *4( h16 ":" ) h16 ] "::"              ls32
                  / [ *5( h16 ":" ) h16 ] "::"              h16
                  / [ *6( h16 ":" ) h16 ] "::"

      ls32        = ( h16 ":" h16 ) / IPv4address
                  ; least-significant 32 bits of address

      h16         = 1*4HEXDIG
                  ; 16 bits of address represented in hexadecimal

    IPv4address = dec-octet "." dec-octet "." dec-octet "." dec-octet

    dec-octet   = DIGIT                 ; 0-9
                / %x31-39 DIGIT         ; 10-99
                / "1" 2DIGIT            ; 100-199
                / "2" %x30-34 DIGIT     ; 200-249
                / "25" %x30-35          ; 250-255

**Comment by hrbrmstr** [comment]
it's at least guaranteed to have the `[]` (i.e. it's an invalid URL/URI w/o it)

**Comment by Ironholds** [comment]
So basically I can futz this by checking, post-scheme identification, whether the first character is [ ? ;)

**Comment by hrbrmstr** [comment]
Well, I didn't want to actually say that, but yes (and it's what I wld do ;-)

**Comment by Ironholds** [comment]
Huh.

I...seem to have fixed it already? This patch is really too simple to have worked. I kind of feel bad that it worked. Oh well!

**Comment by Ironholds** [comment]
@alexcpsec give the latest github push a whirl?

**Comment by alexcpsec** [comment]
@Ironholds worked great for me. Thanks!

**Comment by Ironholds** [comment]
Grand! It'll be up on CRAN as soon as I CBA to deal with the function registration :/
