### ISSUE TITLE
Via SO

### ISSUE THREAD

**Issue by hrbrmstr** [Ironholds/urltools#66]
http://stackoverflow.com/questions/42258600/urltools-retrieving-domains-not-working

**Comment by Ironholds** [comment]
Th. Wha?

**Comment by Ironholds** [comment]
Comment left, at least. I'm not seeing where the bug is (unless the request is for a feature that lets you just extract the domain name, without caring about country-level suffix or subsidiary suffixes?)

**Comment by hrbrmstr** [comment]
didn't really read through it but figured you'd be more apt to see the SO thing if I put a link here :-)
