### ISSUE TITLE
Bug: Confusing domain with "domain-like" thing in fragment

### ISSUE THREAD

**Issue by alexcpsec** [Ironholds/urltools#67]
Hey, Oliver! Let me know if you have some time to look into this

```
> urltools::url_parse("http://realdomain.com/page.html?email=alex@otherdomain.com")
  scheme          domain port path parameter fragment
1   http otherdomain.com <NA> <NA>      <NA>     <NA>
```

**Comment by Ironholds** [comment]
Hm; try with the dev version and see what you see?

**Comment by Ironholds** [comment]
@alexcpsec ping? I'd like to put out a new release soonish

**Comment by alexcpsec** [comment]
Sorry, I’ll get to it today

-- 
Alex Pinto

On April 11, 2017 at 3:52:04 PM, Oliver Keyes (notifications@github.com)
wrote:

@alexcpsec <https://github.com/alexcpsec> ping? I'd like to put out a new
release soonish

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Ironholds/urltools/issues/67#issuecomment-293423147>,
or mute the thread

**Comment by Ironholds** [comment]
Thankee!

**Comment by alexcpsec** [comment]
Looks good, @Ironholds . thanks for helping me with this.

**Comment by Ironholds** [comment]
Noo problem! It'll be in the next production release (coming up soon)
