### ISSUE TITLE
Parameters get overwritten when they're suffixes of other params

### ISSUE THREAD

**Issue by dgrtwo** [Ironholds/urltools#68]
If I have one URL param called `longertest` and one called `test`, the value of the first is replaced by the latter:

    library(urltools)
    param_get("example.com?longertest=hello&", c("test", "longertest"))

Results in:

       test longertest
    1 hello      hello

Note that this doesn't happen if you reverse the order of the query string, as in `test=goodbye&longertest=hello`. Apparently it is finding the first time it matches and not noticing that it is part of a longer parameter name.

**Comment by Ironholds** [comment]
Iiii don't get it. You don't appear to have two parameters?

**Comment by dgrtwo** [comment]
Oops! Example got chopped up at some point when I was pasting it in. Real example is here:

    param_get("example.com?longertest=hello&test=goodbye", c("test", "longertest"))

**Comment by Ironholds** [comment]
Oooh interesting problem. I'm pretty sure I can fix it, although it might have a performance impact.

**Comment by Ironholds** [comment]
latest version:


```
> param_get("example.com?longertest=hello&test=goodbye", c("test", "longertest"))
     test longertest
1 goodbye       ello
```

If you're running this against a lot of params, mind testing the dev version against it? I rewrote it using some integer offset magic and it works but it's also, well, I don't guarantee I know HOW ;)

**Comment by Ironholds** [comment]
Ping pingedy ping

**Comment by dgrtwo** [comment]
In my use cases where it wasn't working before, it now is. Thank you!

I believe one change from old behavior is that giving it a query string without a domain or `?` (e.g. just `param_get("longertest=hello&test=goodbye", c("test", "longertest"))`) results in NAs. If this is the intended behavior that's fine (I have some query strings without domains but can work around the issue eaisly).

Cheers and thanks!

**Comment by Ironholds** [comment]
Oh *fun*. I think I can fix that.

**Comment by Ironholds** [comment]
Mmmn. Okay, 25 seconds later: I probably can't fix that :(. May have to work around with paste()!
