### ISSUE TITLE
url parse and compose cyclic broken for top domain queries

### ISSUE THREAD

**Issue by mzoll** [Ironholds/urltools#71]
it might be a bit irregular to put queries on top domains, but it breaks a lot of stuff when parsed in urltools

`
url <- 'abc.com/?arg1="foo/bar"&arg=42'

url_obj <- url_parse(url)
url_obj['domain']
url_obj['path']
url_obj['parameter']

url_new <- url_compose(url_obj)
url_new #notice '/' after top domain is gone

url_obj_new <- url_parse(url_new)
url_obj_new['domain']
url_obj_new['path']
url_obj_new['parameter']

#bonus
domain(url_obj_new['domain']) #will get that part right again
`

I suspect that you try to break up the url into path/domain before you try splitting of the query. 
I propose to make it the other way around and force the Insertion of a '/' when recomposing the url even if the decomposed path-field is empty.

**Comment by Ironholds** [comment]
Could you show the output of your example in the example, please?

**Comment by Ironholds** [comment]
```
> url_obj
  scheme  domain port path             parameter fragment
1   <NA> abc.com <NA> <NA> arg1="foo/bar"&arg=42     <NA>
> url_obj['domain']
   domain
1 abc.com
> url_obj['path']
  path
1 <NA>
> url_obj['parameter']
              parameter
1 arg1="foo/bar"&arg=42
```

This seems to be performing precisely as it should. What/where is the bug? The lack of a slash in a recomposed URL?

**Comment by mzoll** [comment]
You need also to look at the second part with the url_new_obj!

The problem is that the parts of the cycled url are not correctly resolved , because the middle slash has been removed, which eventually leads to strange behavior if not errors. See below the output (here a domain which contains a question mark etc)

`
> library(urltools)
> 
> url <- 'abc.com/?arg1="foo/bar"&arg=42'
> 
> url_obj <- url_parse(url)
> (d1 <- url_obj['domain'])
   domain
1 abc.com
> (p1 <- url_obj['path'])
  path
1 <NA>
> (a1 <- url_obj['parameter'])
              parameter
1 arg1="foo/bar"&arg=42
> 
> url_new <- url_compose(url_obj)
> url_new #notice '/' after top domain is gone
[1] "abc.com?arg1=\"foo/bar\"&arg=42"
> 
> url_obj_new <- url_parse(url_new)
> (d2 <- url_obj_new['domain'])
             domain
1 abc.com?arg1="foo
> (p2 <- url_obj_new['path'])
         path
1 bar"&arg=42
> (a2 <- url_obj_new['parameter'])
  parameter
1      <NA>
> 
> #to be expected that things before and after cycling url are the same
> d1 == d2
     domain
[1,]  FALSE
> p1 == p2
     path
[1,]   NA
> a1 == a2
     parameter
[1,]        NA
> 
> #bonus
> domain(d2) #error (i guess the internal subroutine does not like certain special characters or something)
Error in eval(substitute(expr), envir, enclos) : 
  not compatible with STRSXP
`

**Comment by Ironholds** [comment]
Gotcha; I'll look into it.

**Comment by Ironholds** [comment]
So the domain(d2) error isn't due to the presence of special characters it's due to the fact that domain() expects a full URL. The other bug, however, should now be fixed.
