### ISSUE TITLE
Theoretical inconsistency on `path` at `url_parse` and `url_compose`

### ISSUE THREAD

**Issue by alexcpsec** [Ironholds/urltools#72]
So here is something that has been bothering me:

```
> pp <- urltools::url_parse("http://example.com/")
> pp
  scheme      domain port path parameter fragment
1   http example.com <NA> <NA>      <NA>     <NA>
> urltools::url_compose(pp)
[1] "http://example.com"
> pp <- urltools::url_parse("http://example.com/1")
> pp
  scheme      domain port path parameter fragment
1   http example.com <NA>    1      <NA>     <NA>
> urltools::url_compose(pp)
[1] "http://example.com/1"
> 
```

_ Techincally_, the `path` variable should have been `/` on the first one and `/1` on the second one, because that is what gets passed on the HTTP verb command. I'm not against using NA to represent the empty `path`, but the `url_compose` command should be re-assembling the URL correctly regardless.

Any thoughts?

**Comment by alexcpsec** [comment]
Oh, I just realized this is related to #71 

Let me take the current `master` for a spin.

**Comment by alexcpsec** [comment]
Yup, nevermind. The #71 fix is exactly this.

**Comment by Ironholds** [comment]
Yay! I need to push the new version.
