### ISSUE TITLE
bug with param_set when key = "key"

### ISSUE THREAD

**Issue by survtools** [Ironholds/urltools#73]
Working code

    url <- ""
    scheme(url) <- "http"
    domain(url) <- "some.url"
    path(url)   <- "api/vectorQuery.xml"
  
    #url         <- param_set(url, key = "key", value = "11111")
    url         <- param_set(url, key = "layer", value = "9")
    url         <- param_set(url, key = "count", value = "8")
    url         <- param_set(url, key = "x", value = "22222")
    url         <- param_set(url, key = "y", value = "33333")
    url         <- param_set(url, key = "radius", value = "7")
    url         <- param_set(url, key = "geometry", value = "true")
    url         <- param_set(url, key = "with_field_names", value = "true")
    url         <- param_set(url, key = "srs", value = "urn:x-ogc:def:crs:EPSG:2105")
  
    print(url)

`http://some.url/api/vectorQuery.xml?layer=9&count=8&x=22222&y=33333&radius=7&geometry=true&with_field_names=true&srs=urn:x-ogc:def:crs:EPSG:2105`

Non working code

    url <- ""
    scheme(url) <- "http"
    domain(url) <- "some.url"
    path(url)   <- "api/vectorQuery.xml"

    url         <- param_set(url, key = "key", value = "11111")
    url         <- param_set(url, key = "layer", value = "9")
    url         <- param_set(url, key = "count", value = "8")
    url         <- param_set(url, key = "x", value = "22222")
    url         <- param_set(url, key = "y", value = "33333")
    url         <- param_set(url, key = "radius", value = "7")
    url         <- param_set(url, key = "geometry", value = "true")
    url         <- param_set(url, key = "with_field_names", value = "true")
    url         <- param_set(url, key = "srs", value = "urn:x-ogc:def:crs:EPSG:2105")

    print(url)

`http://some.url/api/vectorQuery.xml?key=33333&layer=9&count=8&x=22222&radius=7&geometry=true&with_field_names=true&srs=urn:x-ogc:def:crs:EPSG:2105`

Issue: "key" has the value of "y", and "y" is missing.

Rstudio Version 1.0.143
urltools Version 1.6.0

**Comment by Ironholds** [comment]
Ooh, fun! Thanks - I'll dig into this. It shouldn't be doing that.

**Comment by Ironholds** [comment]
Could you try grabbing the development version with `devtools::install_github("ironholds/urltools")` and see if the issue still appears?

**Comment by survtools** [comment]
done, and fixed :)


        url <- ""
        scheme(url) <- "http"
        domain(url) <- "some.url"
        path(url)   <- "api/vectorQuery.xml"
        
        url         <- param_set(url, key = "key", value = "11111")
        url         <- param_set(url, key = "layer", value = "9")
        url         <- param_set(url, key = "count", value = "8")
        url         <- param_set(url, key = "x", value = "22222")
        url         <- param_set(url, key = "y", value = "33333")
        url         <- param_set(url, key = "radius", value = "7")
        url         <- param_set(url, key = "geometry", value = "true")
        url         <- param_set(url, key = "with_field_names", value = "true")
        url         <- param_set(url, key = "srs", value = "urn:x-ogc:def:crs:EPSG:2105")
        
        print(url)


Output

     http://some.url/api/vectorQuery.xml?key=11111&layer=9&count=8&x=22222&y=33333&radius=7&geometry=true&with_field_names=true&srs=urn:x-ogc:def:crs:EPSG:2105
