### ISSUE TITLE
url_encode, forward slash in path encoded as %2f

### ISSUE THREAD

**Issue by survtools** [Ironholds/urltools#74]
Code   
 
    url <- ""
    scheme(url) <- "http"
    domain(url) <- "some.url"
    path(url)   <- "api/vectorQuery.xml"    
    print(url_encode(url))

Output

    http://some.url/api%2fvectorQuery.xml

Rstudio Version 1.0.143
urltools Version 1.6.0

**Comment by Ironholds** [comment]
Do the URLs encode the slash and not work, or just encode the slash?

```
library(urltools)
library(httr)

url <- ""
scheme(url) <- "http"
domain(url) <- "en.wikipedia.org"
path(url)   <- "wiki/Main_Page"    
print(url_encode(url))

# Final URL
[1] "http://en.wikipedia.org/wiki%2fMain_Page"


httr::HEAD(url)

# Response
Response [https://en.wikipedia.org/wiki/Main_Page]
  Date: 2017-07-02 19:50
  Status: 200
  Content-Type: text/html; charset=UTF-8
<EMPTY BODY>
```

This appears to be a repeat of #16 which, to summarise - even though the IETF RfC does not require those characters to be encoded, it's pretty much accepted everywhere with the exception of old, default Apache servers. So there's only a bug here if it produces a problem in production machines you're trying to use.

**Comment by survtools** [comment]
It breaks the URL, sorry this is the correct form of the URL, so the API KEY is alpha numeric and in this case ends with an 8

    http://data.source.com/services;key=APIKEY/wfs?service=WFS&...

**Comment by Ironholds** [comment]
And the slash after APIKEY is being encoded?

That URL violates the URL RfCs in about three different ways - I'm not sure how it'd be possible to encode it in a way that didn't break `APIKEY`, say.

**Comment by survtools** [comment]
Yeah the slash after the APIKEY is the one that is encoded and is then not what the server is expecting. No matter, I can use paste0 and some other function to encode the variable that I need encoded.

cheers!

**Comment by Ironholds** [comment]
Cool! Yeah, that's one zany URL!
