### ISSUE TITLE
Vectorize `path()<-`

### ISSUE THREAD

**Issue by nfultz** [Ironholds/urltools#76]
could the path setter path<- be vectorized and grow the result to the longer of x and value, instead of current behavior:
```
> url <- 'http://github.com'
> path(url) <- c('Ironholds', 'nfultz')
> url
[1] "http://github.com/Ironholds"
```

desired:
[1] "http://github.com/Ironholds" "http://github.com/nfultz"

**Comment by Ironholds** [comment]
And how would that work if 'url' was two URLs? Produce a list?

**Comment by nfultz** [comment]
Normal R behavior is to recycle the shorter of the two vectors.
In psuedo code:

```
> url <- c('http://github.com', 'http://google.com')
> path(url) <- c('Ironholds', 'nfultz')

```
would evaluate to => `[ github.com/Ironholds , google.com/nfultz ]`

**Comment by Ironholds** [comment]
Well, yes, it wouldn't if implemented here. So the final version of the bug is: modify element-setting code to recycle the shorter of the two vectors?

**Comment by nfultz** [comment]
Sounds good.

**Comment by joelgombin** [comment]
+1 for that feature request. Obviously it would be very useful for other setters too (`domain` etc.). It would allow stuffs like:
```r
domain(urls) <- gsub(some_regex, "\\1", domain(urls))
```

**Comment by Ironholds** [comment]
This should now be fixed - could you test?
