### ISSUE TITLE
Improved NA handling on path 

### ISSUE THREAD

**Issue by nfultz** [Ironholds/urltools#77]
Currently, path('http://www.github.com') is NA.  

This means that 

path(x) <- path(x)

sets x to NA.

**Comment by Ironholds** [comment]
And instead it should do what? Not modify it?

**Comment by nfultz** [comment]
It probably makes more sense for path('http://www.github.com')  => '', because:

```
> url <- c('http://google.com/test.txt')
> path(url) <- ''
> path(url)
[1] NA
> url
[1] "http://google.com/"
```

If I set the path to '', I would expect '' to come back out.

**Comment by Ironholds** [comment]
The reason it comes out as NA is that it simplifies checking code; paths are either an actual string or an NA, not (an actual string, or an NA, or an empty string). I'm honestly pretty comfortable with this behaviour in the code.

**Comment by nfultz** [comment]
Would you consider always returning the leading slash then? In HTTP (although not URLS in general), the GET path always starts with /.  Eg when you `curl http://google.com`, it requests `GET /`, not 'GET'.

**Comment by Ironholds** [comment]
Well, it requests `GET /` _when it's the raw domain_. `curl http://google.com/foo` and `curl http://google.com/foo/` hit different locations.

**Comment by nfultz** [comment]
Right, `/foo` and `/foo/`, both have the slash in front.

**Comment by Ironholds** [comment]
Yup, because the path is defined as 'everything after that slash'. I'd honestly recommend just using paste() in this case.
