### ISSUE TITLE
Handle leading slashes on paths for path<-

### ISSUE THREAD

**Issue by nfultz** [Ironholds/urltools#78]
If there is a leading slash on the path we should get rid of it instead of having two after the host.

```
> path(url) <- "/what" 
> url 
[1] "http://github.com//what"  "http://google.com//what"  "http://system1.com//what"
```

**Comment by Ironholds** [comment]
This is an A+ idea, I'll add it to the to-do. Presumably the same should be done with other elements - ie, it'd be simple to check  `scheme(url) <- "https://"`

**Comment by Ironholds** [comment]
Note to self: solve this and 'vectorise' in the same patch by, essentially, replacing/augmenting set_component with more specific alternatives.

**Comment by Ironholds** [comment]
This should now be fixed - could you test?
