### ISSUE TITLE
Delete params from a URL

### ISSUE THREAD

**Issue by nfultz** [Ironholds/urltools#79]
It would be nice to be able to delete all params from a URL. This doesn't quite work:
```
parameters(url) <- NULL
```

**Comment by Ironholds** [comment]
And in the event that there's a fragment?

**Comment by nfultz** [comment]
If you fix the root cause, you probably fix both :)

**Comment by Ironholds** [comment]
You misunderstand my point; in the event that you set the query parameters to NULL, what happens to the fragment?

**Comment by nfultz** [comment]
I do miss your point; Wouldn't the parameters setter only change the
parameters? Wouldn't the fragment setter only change the fragment?

**Comment by Ironholds** [comment]
Yep, which could theoretically cause weirdness. But what the heck, I'll add it to the to-do

**Comment by nfultz** [comment]
Can you add an example of said weirdness? I am having trouble.

**Comment by Ironholds** [comment]
URLs that end up with enough bits NULLed out they're no longer valid, but still have query fragments, kind of thing. As said, I'll work on it.

**Comment by nfultz** [comment]
I think the only required parts are protocol and host, so those should not
be deleteable.

**Comment by Ironholds** [comment]
At which point the API is inconsistent. _sighs_. I'll add it to the to-do.

In the future if you are going to submit feature requests (this goes for everyone) it would be good to have:

1. An example of how it behaves right now
2. An example of how you would like it to behave
3. A rationale for why this is a good thing to have.

**Comment by nfultz** [comment]
I can just keep using my fork, just wanted to share my experience with you.

**Comment by Ironholds** [comment]
It's most appreciated! And I'll be making some tweaks, dinnae worry.

**Comment by Ironholds** [comment]
Heya! Finally found some time to work on this. Can you grab the latest version off GitHub and tell me how it works? Thanks!
