### ISSUE TITLE
parsing schemes like `android-app`

### ISSUE THREAD

**Issue by juliasilge** [Ironholds/urltools#81]
I'm getting some incorrect results parsing URLs with schemes like `android-app`.

``` r
library(urltools)

url_parse("https://com.google.android.gm")
#>   scheme                domain port path parameter fragment
#> 1  https com.google.android.gm <NA> <NA>      <NA>     <NA>
url_parse("android-app://com.google.android.gm")
#>   scheme      domain port                   path parameter fragment
#> 1   <NA> android-app <NA> /com.google.android.gm      <NA>     <NA>
```

The latter there is a real URL from our traffic logs, FWIW.

**Comment by Ironholds** [comment]
*spits coffee* hhwuah. Okay, lemme dig into it? I don't know why it's breaking right there!

**Comment by Ironholds** [comment]
Oh wait, I know why it's breaking - there's an assumption of a maximum character count of 6 before the scheme. This is prrrobably unnecessary - really what we wanna do is just establish that it's also the first `/`. I'll add that bugfix to my weekend and you should have a dev version by work on Monday!

**Comment by Ironholds** [comment]
@juliasilge okay, try the dev version?

**Comment by juliasilge** [comment]
Looks great! Thank you so much for the fix. :dizzy::dizzy::dizzy:

**Comment by Ironholds** [comment]
Yay!
