### ISSUE TITLE
url_parse fails to detect fragment, when url does not have a path OR parameter component

### ISSUE THREAD

**Issue by mkhezr** [Ironholds/urltools#83]
Take the following url:
http://some.website.com#frag

We **expect** urltools::url_parse to break the url into its components like this:

- scheme: http
- domain: some.website.com
- port: NA
- path: NA
- parameter: NA
- fragment: frag

instead, we get:
`urltools::url_parse("http://some.website.com#frag")`
`  scheme                domain port path parameter fragment`
`1   http some.website.com#frag <NA> <NA>      <NA>     <NA>`

Notice how domain includes the "#frag" and fragment is NA. 

Now if I change the url to include either a path or a parameter, urltools will parse correctly:
`urltools::url_parse("http://some.website.com/path#frag`
`  scheme           domain       port   path      parameter fragment`
`1   http some.website.com <NA> path      <NA>     frag`

and with a parameter:
`urltools:url_parse("http://some.website.com?param=value#frag)`
`  scheme           domain port path   parameter fragment`
`1   http some.website.com <NA> <NA> param=value     frag`

**Comment by Ironholds** [comment]
Interesting - thanks! I'll try and fix it soonish.
