### ISSUE TITLE
Punycode ASN issue

### ISSUE THREAD

**Issue by Ironholds** [Ironholds/urltools#84]
As reported at https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-ASAN/urltools/00check.log - @wrathematics , do _you_ know what this means? (I don't off the top of my head. I mean, intellectually, yes, but I don't know if I know how to _fix_ it)

**Comment by wrathematics** [comment]
I don't know. But I can't replicate that error when I test it both locally and on rhub. I don't have a terribly high opinion of asan, frankly. Are you getting demands from CRAN about fixing this? Are you able to replicate this?

The only thing I can even think based on the line numbers from the report (which seem to be off by 1?) is it doesn't like [this line](https://github.com/Ironholds/urltools/blob/master/src/puny.cpp#L180). You might need to split it into two, like:

```c++
std::string tmp = holding.split_url[i].substr(4);
const char *s = tmp.c_str();
```

**Comment by Ironholds** [comment]
Makes sense! Lemme try that..
