### ISSUE TITLE
Assigners and missing values

### ISSUE THREAD

**Issue by dmi3kno** [Ironholds/urltools#88]
I wonder if something can be done about situation when I want to update my url with an element that did not exist before.
```r
url <- "https://www.wikipedia.org/"
urltools::path(url) <- urltools::path("https:://www.wikipedia.org/w/")
#> Error in urltools::path("https://www.wikipedia.org/") <- urltools::path("https:://www.wikipedia.org/w/") : 
#>  target of assignment expands to non-language object
```
I understand that error is thrown because of `path()<-`  attempt to assign "w/" to what used to be NA.

There's definitely a workaround via parsing and recomposing url (fixing NA's in between), but I love accessors so much that I wish I did not have to go that long route.

PS: This will apply to all assigner-accessors, I believe.

**Comment by Ironholds** [comment]
I mean, it could be but I'm pretty sure that it's because you're trying (from R's parser's point of view) to assign an unevaluated expression to an unevaluated expression. What happens if you avoid assigning a path() call to another path() call - if you store it in an intermediate object?

**Comment by Ironholds** [comment]
@dmi3kno did it work?

**Comment by dmi3kno** [comment]
Can not reproduce the error anymore. Not sure what happened. Closing the issue.
