### ISSUE TITLE
Flag -UNDEBUG causes crash in latest Rcpp

### ISSUE THREAD

**Issue by jeroen** [Ironholds/urltools#89]
CRAN probably already told you this, but your Makevars file has a debugging flag:

```make
PKG_CPPFLAGS = -UNDEBUG
```

The latest version of Rcpp now aborts on type errors when debugging (see https://github.com/RcppCore/Rcpp/pull/860)

```r
urltools::parameters(mtcars)
```

As seen in the wild by the crul package: https://cran.r-project.org/web/checks/check_results_crul.html

**Comment by Ironholds** [comment]
Yeah, CRAN is (slowly working through) accepting my patch which fixes it.

**Comment by jeroen** [comment]
Why is this flag needed in the first place?

**Comment by Ironholds** [comment]
It's not, that's why I'm removing it.

**Comment by jeroen** [comment]
Fix on CRAN, thanks!
