### ISSUE TITLE
Consider alternate name to path

### ISSUE THREAD

**Issue by hammer** [Ironholds/urltools#93]
Thanks for the great library! I often use `urltools` together with https://github.com/r-lib/fs and https://github.com/jeroen/curl to download data to my local filesystem. Since both `fs` and `urltools` export `path`, I end up needing to use `urltools::path` and `fs::path` everywhere in my code.

I feel like the path handling in `fs` is more common so it would make the most sense to rename `path` in this library. It's definitely a pain to evolve an API so no worries if you have better things to do--just thought I'd toss this idea out.

**Comment by Ironholds** [comment]
Um. I mean, to be honest, if there is a collision in language here that should be resolved I would suggest taking it up with the person who chose 'path' as a term of art for this component, a [https://tools.ietf.org/html/rfc3986#section-3.3 Mr T. Berners-Lee]
