### ISSUE TITLE
Multiple parameter values not handled by param_get

### ISSUE THREAD

**Issue by alinebra** [Ironholds/urltools#94]
Hi :) 
It's an awesome package you got here. Gratz!

My issue is quite similar, but no, with #68.
I have some parameters that can assume multiple values on the same url, and param_get only returns the first value.

An example:
https://www.qconcursos.com/questoes-de-concursos/questoes?advanced_filter_toggle_input=on&q=&discipline_ids%5B%5D=213&discipline_ids%5B%5D=33&subject_ids%5B%5D=15744&subject_ids%5B%5D=21960&examining_board_ids%5B%5D=2&exclude_nullified=true&exclude_outdated=true

discipline_ids%5B%5D and subject_ids%5B%5D have 2 values each. 
Is it possible to extract both using the param_get ?

**Comment by hrbrmstr** [comment]
It doesn't look like it currently handles that but a temporary workaround could be to use `httr::parse_url()` for known multi-param URLs:

```r
str(httr::parse_url("https://www.qconcursos.com/questoes-de-concursos/questoes?advanced_filter_toggle_input=on&q=&discipline_ids%5B%5D=213&discipline_ids%5B%5D=33&subject_ids%5B%5D=15744&subject_ids%5B%5D=21960&examining_board_ids%5B%5D=2&exclude_nullified=true&exclude_outdated=true")$query, 1)
## List of 9
##  $ advanced_filter_toggle_input: chr "on"
##  $ q                           : chr ""
##  $ discipline_ids[]            : chr "213"
##  $ discipline_ids[]            : chr "33"
##  $ subject_ids[]               : chr "15744"
##  $ subject_ids[]               : chr "21960"
##  $ examining_board_ids[]       : chr "2"
##  $ exclude_nullified           : chr "true"
##  $ exclude_outdated            : chr "true"
```

**Comment by alinebra** [comment]
Thank you :) I'll try working with it.
