### ISSUE TITLE
Trouble with Non-Ascii URL

### ISSUE THREAD

**Issue by prognos-kwe** [Ironholds/urltools#97]
It seems that urltools::url_parse has trouble with URL like

x <- "www.cordes-tiefkühlprodukte.de"

A more detail description is at

https://stackoverflow.com/questions/57060536/using-urltoolsurl-parse-with-utf-8-domains

**Comment by hrbrmstr** [comment]
Pretty sure you just need to make sure the URL parsing bits of code are working in UTF-8 encoding. I do not have any issues parsing that URL

**Comment by prognos-kwe** [comment]
Ok, thanks for looking into it. I found a way to make it work as posted at stackoverflow.
