### ISSUE TITLE
suffix_extract fails when passing in refreshed suffix data.frame

### ISSUE THREAD

**Issue by bjedwards** [Ironholds/urltools#99]
Currently `suffix_extract` fails when providing a refreshed `suffixes` argument. Example

```R
new_suffices <- suffix_refresh()
suffix_extract('en.wikipedia.com', suffixes = new_suffices)
```

Resulting in 
```
Error: $ operator is invalid for atomic vectors
```

This appears to be because of the use of `$` [here](https://github.com/Ironholds/urltools/blob/master/R/suffix.R#L142) it currently reads, 
```R
suffixes <- suffixes$suffixes
```

but should read 

```R
suffixes <- suffixes[['suffixes', exact=FALSE]]
```
The `exact=FALSE` maintains the same semantics according to the `$` documentation. 

I can submit a pull request shortly to fix the issue. This begs the question on the use of `$` vs `[[]]`. My understanding is that `$` should only be used in interactive work, but I can't find any formal reference to the practice.

**Comment by Ironholds** [comment]
Thanks!
